* GUI FTW! -- WTF?

  GUI FTW! is a *declarative* GUI library.

  Features:
  - Supports both *Swing* and *SWT* as backends.
  - Declare your GUI structure using simple Clojure syntax. No XML!
  - Style it in a CSS fashion.
  - Put event handlers in stylesheets.

  Planned features:
  - Bind data from widgets to Clojure's agents, atoms, vars, etc.

* Status

  It works. It's in alpha stage, that means some things will change
  and it's a little rough on the edges.

  Instead of wiki, I've written two analogical examples for Swing and
  SWT with lots of comments. They're [[https://github.com/santamon/GUIFTW/blob/master/src/guiftw/examples/swing/basic.clj][here]] and [[https://github.com/santamon/GUIFTW/blob/master/src/guiftw/examples/swt/basic.clj][here]]. I recommend
  reading Swing example first and then SWT one as the latter contains
  only Swing-SWT differences.

* Disclaimer (Questions One Would Probably Ask)

  1. *Do I have to know Swing or SWT to use GUI FTW?*

     Yes. GUI FTW is responsible for generating redundant code you
     would write without it and providing more *declarative* approach
     to creating GUIs with Swing or SWT. Still, you have to know the
     toolkit you are using (classes names, properties, event
     listeners, etc.).

  2. *Can I run the same code against SWT and Swing?*
     
     Not at this point and it's not planned for the future. GUI FTW is
     portable across these toolkits because it's very abstract but
     your code created using it won't be (you'll be using specific
     classes, properties and event listeners to your toolkit of
     choice). Probably writing such a bridge could be done but its not
     in scope of this project (look at the other exciting features
     implemented and planned on the top of this README! ;) ).

  3. *Could support for framework X be added?*

     Probably yes. I know Swing and a little of SWT so GUI FTW was
     created keeping their similarities in mind. BUT: core of the
     framework is completely independent of one or the
     other. Technically writing support for another framework is
     writing one function that is responsible for creating object
     (like [[https://github.com/santamon/GUIFTW/blob/master/src/guiftw/swing.clj][swing-create]] or [[https://github.com/santamon/GUIFTW/blob/master/src/guiftw/swt.clj][swt-create]]).
